# -*- coding: utf-8 -*-
"""Glosarul de termeni folosit in foaia 04_DICTIONAR.

Fiecare intrare: (Termen, Categorie, Ce inseamna, De ce conteaza pentru EQUIL,
                  Cum il ceri / exemplu concret)
"""

DICTIONAR = [
    # ---------------------------------------------------------- proces
    ("NDA (Non-Disclosure Agreement)", "Proces",
     "Acord de confidențialitate. Un contract scurt prin care te obligi să nu divulgi și să nu folosești în alt scop datele primite.",
     "Fără el, majoritatea firmelor serioase nu îți dau cifre reale. Îl semnezi înainte de prima cerere de date.",
     "„Vă propun să semnăm un acord de confidențialitate înainte să îmi trimiteți orice cifră. Aveți un model al dumneavoastră sau folosim al meu?”"),
    ("Kickoff", "Proces",
     "Întâlnirea de start a proiectului, în care stabilești obiectivul, perioada analizată, cine ce dă și până când.",
     "Aici completezi 01_FIRMA și 02_CONTACTE. Un kickoff bun scurtează colectarea cu săptămâni.",
     "„Propun o oră împreună la început, ca să stabilim exact ce ne uităm și cine îmi trimite ce.”"),
    ("Data kickoff", "Proces",
     "Data la care a avut loc întâlnirea de start. Este ziua zero a proiectului.",
     "De la ea numeri termenele. Dacă livrarea întârzie, de aici vezi unde s-a pierdut timpul.",
     "Se completează în 01_FIRMA, secțiunea MANDAT EQUIL."),
    ("Data owner", "Proces",
     "Persoana din firmă care deține efectiv un set de date și îl poate scoate din sistem.",
     "Nu firma îți dă datele, ci un om anume. Foaia 02_CONTACTE există exact pentru asta.",
     "„Cine, concret, poate scoate din ERP lista de facturi pe ultimele 24 de luni?”"),
    ("Stakeholder / decident", "Proces",
     "Persoana care ia decizia finală și aprobă bugetele. Nu e întotdeauna cine te-a contactat.",
     "Raportul trebuie scris pentru decident. Dacă el nu e în discuție, concluziile rămân pe hârtie.",
     "„Cine semnează la final pentru acțiunile pe care le propunem?”"),
    ("Scope / mandat", "Proces",
     "Ce intră și ce NU intră în proiect: ce perioadă, ce linii de business, ce nu analizăm.",
     "Previne extinderea nelimitată a muncii („dar puteți să vă uitați și la...”).",
     "„Ne uităm la vânzări și clienți pe ultimele 24 de luni. Stocurile și producția nu intră acum.”"),
    ("Livrabil (deliverable)", "Proces",
     "Rezultatul concret pe care îl predai: în cazul nostru, raportul din 40_RAPORT plus planul de acțiuni.",
     "Clientul trebuie să știe din prima ce primește, ca să nu aibă alte așteptări.",
     "„La final primiți un raport cu 5 oportunități prioritizate și un plan pe 30 de zile.”"),
    ("Follow-up", "Proces",
     "Revenirea cu o solicitare sau o acțiune după o discuție. În colectarea de date, reamintirea politicoasă.",
     "Datele întârzie aproape întotdeauna. Două-trei follow-up-uri scurte sunt normale, nu insistență.",
     "„Vă reamintesc de exportul din ERP — de el depinde restul analizei. Puteți până vineri?”"),
    ("Workshop", "Proces",
     "Sesiune de lucru cu mai mulți oameni din firmă, în care validezi concluziile și construiești planul.",
     "Oportunitățile validate împreună cu echipa se execută. Cele trimise pe email, mai rar.",
     "„Propun 90 de minute cu echipa de vânzări, să validăm împreună ce am găsit.”"),
    ("GDPR", "Proces",
     "Regulamentul european de protecție a datelor personale. Numele, emailul sau telefonul unei persoane sunt date personale.",
     "Pentru NPS și pentru echipă, cere date anonimizate (inițiale sau ID-uri) dacă nu ai un temei clar.",
     "„Îmi puteți trimite lista cu inițiale în loc de nume complete? Analiza funcționează la fel.”"),

    # ---------------------------------------------------------- sisteme
    ("ERP", "Sisteme",
     "Enterprise Resource Planning — programul central în care firma ține facturi, stocuri, furnizori, uneori contabilitatea. „Sistemul în care se face factura.”",
     "Sursa principală pentru vânzări, clienți, produse și costuri. Fără el, datele vin din Excel-uri paralele, cu erori.",
     "„În ce program emiteți facturile?” Exemple în România: SAGA, WinMentor, Smartbill, Nexus, Charisma, SAP, Oracle NetSuite."),
    ("Sistem de facturare", "Sisteme",
     "Varianta mai simplă a unui ERP: doar emite facturi și ține clienții. Multe firme mici au doar atât.",
     "E suficient pentru analiză. Are aproape mereu export în Excel sau CSV.",
     "„Puteți exporta facturile pe 24 de luni în Excel?” Exemple: Smartbill, Oblio, FGO, Facturis."),
    ("CRM", "Sisteme",
     "Customer Relationship Management — programul în care echipa de vânzări ține clienții, discuțiile, ofertele și oportunitățile.",
     "De aici vin segmentul, canalul, responsabilul de cont și pipeline-ul. Multe firme mici au CRM-ul „în Excel” sau în capul directorului de vânzări.",
     "„Unde țineți evidența discuțiilor cu clienții și a ofertelor?” Exemple: HubSpot, Pipedrive, Salesforce, Zoho, Excel."),
    ("WMS", "Sisteme",
     "Warehouse Management System — programul de gestiune a depozitului: stocuri, livrări, termene.",
     "Relevant când NPS-ul scade din cauza livrărilor, nu a produsului sau a prețului.",
     "„Aveți un program separat pentru depozit sau livrările se văd tot în ERP?”"),
    ("Ticketing / helpdesk", "Sisteme",
     "Programul în care se înregistrează reclamațiile și cererile clienților.",
     "Cea mai bogată sursă de cauze concrete pentru detractorii din NPS.",
     "„Reclamațiile se înregistrează undeva sau se rezolvă pe telefon?” Exemple: Zendesk, Freshdesk, Jira Service Management."),
    ("Instrument de raportare / BI", "Sisteme",
     "Program care construiește rapoarte și grafice peste datele din ERP/CRM. BI = Business Intelligence.",
     "Dacă firma are deja așa ceva, datele sunt probabil curate și colectarea durează ore, nu săptămâni.",
     "„Aveți deja rapoarte automate sau totul se face manual în Excel?” Exemple: Power BI, Looker Studio, Tableau, Qlik."),
    ("Export CSV / XLSX", "Sisteme",
     "Descărcarea datelor din program într-un fișier tabelar. CSV = text simplu, separat prin virgulă. XLSX = fișier Excel.",
     "Ai nevoie de asta, nu de PDF. Dintr-un PDF datele se recuperează greu și cu erori.",
     "„Am nevoie de export în Excel sau CSV, nu în PDF — altfel nu pot calcula nimic peste ele.”"),
    ("API / integrare", "Sisteme",
     "Modalitate prin care două programe schimbă date automat, fără ca cineva să exporte manual.",
     "Nu e necesar pentru MVP. Devine util când vrei raportul actualizat lunar, fără muncă manuală.",
     "„Pe termen lung putem lua datele automat; deocamdată un export lunar e suficient.”"),
    ("Master data / nomenclator", "Sisteme",
     "Listele de bază ale firmei: clienți, produse, angajați. Nu conțin tranzacții, ci definiții.",
     "Foile 10_CLIENTI, 11_PRODUSE și 12_OAMENI sunt exact asta. Fără ele, tranzacțiile sunt doar coduri.",
     "„Îmi trimiteți și lista de clienți și cea de produse, nu doar facturile?”"),
    ("SKU", "Sisteme",
     "Stock Keeping Unit — codul unic al unui produs sau serviciu. „Referința” din catalog.",
     "Este cheia după care se leagă vânzările de produse. Un SKU = un rând în 11_PRODUSE.",
     "„Fiecare produs are un cod unic în sistem? Acela îmi trebuie, nu doar denumirea.”"),

    # ---------------------------------------------------------- financiar
    ("CUI", "Financiar",
     "Codul Unic de Înregistrare al firmei la ANAF. Identificatorul fiscal.",
     "Identifică firma fără ambiguitate, chiar dacă își schimbă numele comercial.",
     "Se găsește pe orice factură a firmei."),
    ("CAEN", "Financiar",
     "Codul care descrie activitatea principală a firmei (Clasificarea Activităților din Economia Națională).",
     "Determină cu ce benchmark-uri de industrie compari rezultatele.",
     "„Care e codul CAEN principal?” — sau îl citești din datele publice ale firmei."),
    ("Venit net / cifră de afaceri", "Financiar",
     "Banii încasați din vânzări, fără TVA și după discount.",
     "Este baza tuturor calculelor din fișier. Coloana Revenue_Net din 13_VANZARI.",
     "„Cifrele sunt fără TVA, corect? Am nevoie de valoarea netă, după discount.”"),
    ("TVA", "Financiar",
     "Taxa pe valoarea adăugată. Se adaugă peste prețul net și se virează statului; nu e venitul firmei.",
     "Dacă unii clienți îți dau cifre cu TVA și alții fără, comparațiile ies greșite cu ~19%.",
     "„Verificăm o factură împreună, ca să fiu sigur că vorbim despre aceeași bază.”"),
    ("COGS / cost direct", "Financiar",
     "Cost of Goods Sold — costul direct al a ceea ce ai vândut: marfa, materialul, ora de manoperă. Nu include chiria sau salariile administrative.",
     "Fără COGS nu poți calcula profitul brut, deci nici oportunitățile de marjă.",
     "„Pentru fiecare linie de vânzare, care e costul direct al produsului? Nu costurile generale ale firmei.”"),
    ("Profit brut", "Financiar",
     "Venit net minus COGS. Cât rămâne din vânzare înainte de cheltuielile generale.",
     "Se calculează automat în fișier. Este indicatorul care spune dacă o creștere de vânzări chiar aduce bani.",
     "Coloana Gross_Profit din 13_VANZARI, calculată automat."),
    ("Marjă brută %", "Financiar",
     "Profit brut împărțit la venit net, exprimat procentual. „Din 100 de lei vânduți, câți rămân.”",
     "Semnalul cel mai frecvent: vânzări în creștere, dar marjă în scădere, înseamnă că se crește prin discount.",
     "„Ce marjă considerați normală în domeniul dumneavoastră?” — răspunsul intră în 09_PARAMETRI."),
    ("P&L / cont de profit și pierdere", "Financiar",
     "Raportul care arată veniturile, costurile și profitul pe o perioadă.",
     "Îl folosești ca să verifici dacă suma facturilor primite se potrivește cu realitatea contabilă.",
     "„Îmi puteți da P&L-ul pe ultimele 24 de luni, măcar la nivel de total?”"),
    ("Balanță", "Financiar",
     "Situația contabilă lunară cu toate conturile și soldurile lor.",
     "Sursa de validare pentru venituri și costuri. Nu ai nevoie de tot, doar de conturile de venituri și cheltuieli directe.",
     "„Balanța pe lunile analizate, doar clasele de venituri și cheltuieli, e suficientă.”"),
    ("Cheltuieli fixe", "Financiar",
     "Costuri care apar indiferent cât vinzi: chirie, salarii administrative, abonamente, leasing.",
     "Cu ele afli pragul de rentabilitate și impactul real al unei oportunități.",
     "„Aproximativ cât înseamnă lunar costurile care merg oricum, chiar dacă nu vindeți nimic?”"),
    ("Cash-flow", "Financiar",
     "Mișcarea efectivă a banilor în conturi. Diferit de profit: poți fi profitabil și fără bani, dacă nu te plătesc clienții.",
     "Explică de ce un client „bun” poate fi de fapt o problemă: cumpără mult, dar plătește la 120 de zile.",
     "„Aveți clienți care cumpără bine, dar plătesc greu?”"),
    ("Termen de plată", "Financiar",
     "Numărul de zile în care clientul are voie să plătească factura.",
     "Un termen mare la un client mare blochează capital de lucru. Intră în discuția de risc.",
     "Coloana Payment_Terms_Days din 10_CLIENTI."),
    ("Limită de credit", "Financiar",
     "Plafonul maxim pe care un client îl poate avea neplătit la un moment dat.",
     "Arată cât de mult se expune firma la un singur client.",
     "Coloana Credit_Limit din 10_CLIENTI."),
    ("Buget / țintă", "Financiar",
     "Valoarea planificată pentru o perioadă: cât își propune firma să vândă.",
     "Fără țintă nu poți calcula gap-ul, iar gap-ul e punctul de plecare al oportunităților.",
     "„Aveți un buget de vânzări pe luni? Chiar și aproximativ, e mai bun decât nimic.”"),
    ("Discount", "Financiar",
     "Reducerea acordată față de prețul de listă, în valoare sau procent.",
     "Discountul crescător este cauza cea mai frecventă a erodării marjei.",
     "„Discountul se vede separat pe factură sau e deja scăzut din preț?”"),

    # ---------------------------------------------------------- comercial
    ("B2B / B2C", "Comercial",
     "Business to Business = vinzi către alte firme. Business to Consumer = vinzi către persoane fizice.",
     "Schimbă complet interpretarea: în B2B ai puțini clienți mari, în B2C mulți clienți mici.",
     "„Vindeți în principal către firme sau către persoane fizice?”"),
    ("Canal de vânzare", "Comercial",
     "Drumul pe care ajunge produsul la client: retail, en-gros, online, direct, prin parteneri.",
     "Marja diferă mult între canale. Un mix care se schimbă explică o marjă care scade fără motiv aparent.",
     "Coloana Channel din 10_CLIENTI."),
    ("Segment de client", "Comercial",
     "Gruparea clienților după mărime sau tip: Key Account, Mid-market, Small, Online.",
     "Permite comparații corecte: un client mic nu se compară cu unul mare.",
     "„Cum vă împărțiți intern clienții? Aveți categorii?”"),
    ("Key Account", "Comercial",
     "Client mare, strategic, de obicei cu responsabil dedicat.",
     "Concentrează venitul și riscul. Plecarea unuia singur poate muta rezultatul anului.",
     "„Care sunt primii 5 clienți ca valoare și cine se ocupă de ei?”"),
    ("Pipeline", "Comercial",
     "Totalitatea oportunităților de vânzare aflate în lucru, pe etape, până la semnare.",
     "Arată dacă ținta e realizabilă: fără pipeline suficient, gap-ul nu se acoperă.",
     "„Aveți o listă a oportunităților în lucru, cu valoare și stadiu?”"),
    ("Lead / prospect", "Comercial",
     "Lead = contact interesat, încă necalificat. Prospect = contact calificat, care chiar poate cumpăra.",
     "Relevant pentru creșterea prin clienți noi, nu prin clienții existenți.",
     "„Câți clienți noi ați adus în ultimele 12 luni și de unde au venit?”"),
    ("Cross-sell", "Comercial",
     "Să vinzi un produs în plus unui client existent. „Cumpără X, dar nu și Y.”",
     "Cea mai ieftină creștere: clientul te cunoaște deja, nu mai plătești achiziția lui.",
     "Se vede automat în 22_ANALIZA_PRODUSE, la penetrare."),
    ("Up-sell", "Comercial",
     "Să vinzi aceluiași client o variantă mai mare sau mai scumpă din ce cumpără deja.",
     "Crește valoarea medie pe client fără efort de achiziție.",
     "„Există o variantă premium pe care o cumpără doar o parte din clienți?”"),
    ("Churn / client pierdut", "Comercial",
     "Clientul care nu mai cumpără deloc. Churn rate = procentul de clienți pierduți într-o perioadă.",
     "Un churn mare anulează orice creștere: torni apă într-o găleată găurită.",
     "Semnalul „Client pierdut” din 21_ANALIZA_CLIENTI."),
    ("Client dormant", "Comercial",
     "Client care a cumpărat în trecut, dar nu a mai cumpărat de un număr de zile stabilit de tine.",
     "Între activ și pierdut. Aici reactivarea încă funcționează și costă puțin.",
     "Pragul se setează în 09_PARAMETRI (implicit 90 de zile)."),
    ("Reactivare", "Comercial",
     "Acțiunea prin care aduci înapoi un client dormant.",
     "De obicei cea mai ușoară oportunitate din listă: probabilitate mare, efort mic.",
     "„Când ați contactat ultima dată clienții care nu au mai comandat de 3 luni?”"),
    ("Concentrare / risc de concentrare", "Comercial",
     "Cât din venit vine de la un singur client sau de la primii câțiva.",
     "Peste 20-25% pe un singur client, firma nu mai negociază de pe poziție de forță.",
     "Se calculează automat în 20_KPI și 21_ANALIZA_CLIENTI."),
    ("Penetrare", "Comercial",
     "Ce procent din clienți cumpără un anumit produs.",
     "Produs bun cu penetrare mică = oportunitate clară de campanie dedicată.",
     "Coloana „Penetrare în baza de clienți” din 22_ANALIZA_PRODUSE."),
    ("Venit recurent vs. one-off", "Comercial",
     "Recurent = se repetă automat (abonament, contract anual). One-off = vânzare unică.",
     "Venitul recurent e mult mai valoros: e previzibil și nu trebuie revândut lunar.",
     "„Aveți contracte care se reînnoiesc automat?”"),
    ("Venit mediu pe client (ARPU)", "Comercial",
     "Average Revenue Per User/Account — venit total împărțit la numărul de clienți activi.",
     "Spune dacă creșterea vine din clienți noi sau din adâncirea relației cu cei existenți.",
     "Calculat automat în 20_KPI."),

    # ---------------------------------------------------------- oameni
    ("FTE", "Oameni",
     "Full-Time Equivalent — normă întreagă echivalentă. 1 = program complet, 0,5 = jumătate de normă.",
     "Permite comparații corecte: 4 oameni part-time nu înseamnă 4 oameni.",
     "„Câți dintre ei sunt cu normă întreagă și câți part-time?”"),
    ("Quota / țintă individuală", "Oameni",
     "Ținta de vânzări atribuită unei persoane pentru o perioadă.",
     "Fără ea nu poți spune dacă cineva e sub performanță sau doar are un portofoliu mai mic.",
     "„Fiecare om de vânzări are o țintă lunară?”"),
    ("Coaching / shadowing", "Oameni",
     "Coaching = lucrezi 1-la-1 pe abilități concrete. Shadowing = cineva însoțește un coleg mai bun ca să învețe.",
     "Cele mai ieftine acțiuni pentru oportunitățile de tip „Dezvoltare oameni”.",
     "Apare ca acțiune recomandată în 30_OPORTUNITATI."),
    ("Fluctuație / turnover", "Oameni",
     "Rata cu care pleacă oamenii din firmă într-o perioadă.",
     "Fluctuația mare în vânzări explică pierderea de clienți: pleacă omul, pleacă relația.",
     "„Câți oameni din vânzări au plecat în ultimul an?”"),

    # ---------------------------------------------------------- masurare
    ("KPI", "Măsurare",
     "Key Performance Indicator — indicator cheie de performanță. Un număr care spune dacă lucrurile merg bine.",
     "Foaia 20_KPI îi calculează automat. Un KPI fără comparație nu spune nimic.",
     "„Ce cifre vă uitați acum, lunar?”"),
    ("NPS", "Măsurare",
     "Net Promoter Score. Se pune o singură întrebare: „Pe o scară de la 0 la 10, cât de probabil ne-ați recomanda?”. Scor = % promotori − % detractori, de la −100 la +100.",
     "Cel mai simplu indicator de relație cu clientul. Prezice pierderea clienților înainte să apară în vânzări.",
     "„Ați întrebat vreodată clienții cât de probabil v-ar recomanda?”"),
    ("Promotor / Pasiv / Detractor", "Măsurare",
     "Promotor = scor 9-10. Pasiv = 7-8. Detractor = 0-6. Pasivii nu intră în formulă.",
     "Detractorii sunt lista ta de acțiuni imediate; promotorii sunt sursa de recomandări.",
     "Se calculează automat în 15_NPS, coloana NPS_Category."),
    ("Benchmark", "Măsurare",
     "Valoare de referință față de care compari: media industriei, anul trecut sau cel mai bun din echipă.",
     "Fără referință, „marjă de 22%” nu înseamnă nici bine, nici rău.",
     "Pragurile din 09_PARAMETRI joacă acest rol până ai date de industrie."),
    ("Perioadă de comparație / YoY", "Măsurare",
     "YoY = Year over Year, aceeași perioadă din anul anterior. Alternativ, perioada imediat anterioară.",
     "Comparația cu anul trecut elimină sezonalitatea; cea cu perioada anterioară arată dinamica recentă.",
     "Se setează în 09_PARAMETRI."),
    ("Δ (delta)", "Măsurare",
     "Diferența dintre două valori. Δ% = variația procentuală.",
     "Coloanele Δ și Δ% din 20_KPI. Verde = creștere, roșu = scădere.",
     "—"),
    ("Sezonalitate", "Măsurare",
     "Variația normală, repetabilă, a vânzărilor în cursul anului.",
     "Fără ea, o scădere în august pare o criză, când de fapt e concediu.",
     "„Care sunt lunile bune și lunile slabe, în mod normal?”"),

    # ---------------------------------------------------------- excel
    ("Celulă calculată (formulă)", "Excel",
     "Celulă care își ia valoarea dintr-un calcul, nu din tastatură. În fișier sunt colorate gri.",
     "Dacă scrii peste ele, se pierde calculul și cifrele devin greșite fără să te anunțe nimeni.",
     "Regula: scrii doar în celulele galbene."),
    ("Validare de date (dropdown)", "Excel",
     "Listă predefinită din care alegi, în loc să scrii liber.",
     "Previne „Retail”, „retail” și „RETAIL” ca trei valori diferite, care strică orice grupare.",
     "Listele se editează în 90_LISTE."),
    ("Filtru", "Excel",
     "Butonul din antetul tabelului care ascunde rândurile care nu te interesează.",
     "Așa citești rapid doar semnalele: filtrezi coloana „Semnal” pe ce vrei să vezi.",
     "Se activează din săgeata de pe antet."),
    ("Recalculare", "Excel",
     "Refacerea tuturor calculelor. Se întâmplă automat; se poate forța cu F9 (Ctrl+Shift+F9 pentru tot fișierul).",
     "Dacă cifrele par blocate după ce ai lipit date noi, apasă F9.",
     "—"),
    ("Formatare condiționată", "Excel",
     "Colorarea automată a celulelor în funcție de valoare sau text.",
     "Prioritățile HIGH/MEDIUM/LOW și semnalele se colorează singure.",
     "—"),

    # ---------------------------------------------------------- piata
    ("Concurent direct / indirect", "Piață",
     "Direct = vinde același lucru, acelorași clienți. Indirect = rezolvă aceeași nevoie, altfel (un client poate alege să nu cumpere deloc și să facă singur).",
     "În tabelul de concurență intră doar cei la care firma chiar pierde vânzări, nu toți din județ.",
     "„La cine ați pierdut ultimele trei lucrări? Aceia sunt concurenții.”"),
    ("Cotă de piață", "Piață",
     "Cât din vânzările totale ale unei piețe îi revin unei firme.",
     "Rareori se poate calcula exact: nimeni nu știe cât valorează toată piața locală.",
     "Dacă nu ai cifra pieței, lasă câmpul gol și folosește cota în grupul urmărit."),
    ("Cotă în grupul urmărit", "Piață",
     "Cifra firmei împărțită la cifra tuturor firmelor din tabelul tău de concurență.",
     "E o cifră onestă: nu pretinde că știe toată piața, dar arată poziția față de cei care contează.",
     "Se calculează automat în foaia de concurență."),
    ("Date publice ale firmelor", "Piață",
     "Cifra de afaceri, profitul și numărul de angajați ai oricărei firme din România, depuse anual la ANAF și disponibile public.",
     "Îți dau cifrele concurenților fără să întrebi pe nimeni. Sunt vechi de un an, dar sunt reale.",
     "Se caută după CUI sau după denumire, pe site-urile care agregă bilanțurile."),
    ("Google Business Profile", "Piață",
     "Fișa gratuită a firmei în Google și pe hartă: adresă, program, poze, recenzii, nota medie.",
     "E primul lucru pe care îl vede un client nou. O firmă fără fișă, sau cu una nesetată, pierde clienți înainte să vorbească cu ei.",
     "„Căutați-vă firma pe Google, de pe telefonul altcuiva. Ce vedeți?”"),
    ("Recenzie (review)", "Piață",
     "Părerea publică a unui client, pe Google, Facebook sau altă platformă, de obicei cu o notă de la 1 la 5.",
     "Nota medie contează mai puțin decât numărul de recenzii și decât ce scrie în cele de 1-2 stele.",
     "„Când v-ați citit ultima dată recenziile? Ce reclamă cel mai des?”"),
    ("Scor de percepție", "Măsurare",
     "Media dintre ce se vede public (recenzii) și evaluarea structurată a unui specialist, adusă pe o scară 0-100.",
     "Ține locul NPS-ului la firmele care nu au măsurat niciodată nimic. Nu îl înlocuiește: măsoară ce cred străinii și ce vede un profesionist, nu ce cred clienții care plătesc.",
     "Se calculează automat din foaia „Ce cred oamenii despre firmă”."),
    ("Benchmark competitiv", "Măsurare",
     "Compararea firmei cu concurenții pe aceleași criterii: notă publică, număr de recenzii, preț, mărime.",
     "O notă de 4,1 nu spune nimic singură. Devine concluzie când concurenții sunt la 4,7.",
     "„Hai să ne uităm împreună la ce scrie lumea despre primii trei concurenți.”"),
]
